url: http://ianha.com
title: Up and To The Right
description: 'My name is Ian Ha and I&#039;m a software developer living in New York. I&#039;m interested in startups, design and fashion. You can reach me at ian (at) ianha.com'
email: ian@ianha.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Ian Ha and I'm a software developer living in New York.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ianha.com"
twitter_username: ianpha
github_username:  ianha
